.eslintignore
app.js
app/common/base_model.js
app/common/tools.js
app/controller/site.js
app/extend/application.js
app/extend/helper.js
app/middleware/auth_user.js
app/middleware/locals.js
app/model/message.js
app/model/reply.js
app/model/topic.js
app/model/topic_collect.js
app/model/user.js
app/router.js
app/service/at.js
app/service/cache.js
app/service/message.js
app/service/reply.js
app/service/topic.js
app/service/topic_collect.js
app/service/user.js
config/config.default.js
config/config.local.js
config/plugin.js
package.json
test/app/controller/home.test.js
test/app/service/user.test.js

change:
- replace redis with egg-redis
- replace mongoose with egg-mongoose
- split scheme from service to model
- config: add config.${env}.js
- eslint: ignore app/public & fix error

refactor: redis & mongoose

---

.travis.yml
app/controller/rss.js
app/controller/topic.js
app/extend/helper.js
app/router.js
package.json
test/app/controller/site.test.js
test/app/controller/topic.test.js

close https://github.com/cnodejs/egg-cnode/issues/22

test: travis services

---

package.json

deps: upgrade loader-koa

---

app/controller/page.js
app/controller/sign.js
app/controller/site.js
config/config.default.js

refactor: ejs default layout

---

app/controller/user.js
app/router.js
app/view/sidebar.html
app/view/user/collect_topics.html
app/view/user/index.html
app/view/user/replies.html
app/view/user/stars.html
app/view/user/top100.html
app/view/user/top100_user.html
app/view/user/topics.html
app/view/user/user.html

refactor:
- user page: personal home, collectTopics, topics, replies, stars, top100
- unexisted user page
TODO:
- user setting page(need auth module)
- handle admin post(need auth module)
- UT

refactor: User module frist commit

---

app/middleware/admin_required.js
app/middleware/user_required.js
app/router.js

 middleware: add userRequired & adminRequired

---

app/controller/sign.js
app/middleware/admin_required.js
app/middleware/user_required.js
app/router.js
app/service/at.js
app/view/sign/search_pass.html
config/config.default.js
test/app/controller/sign.test.js
test/app/service/user.test.js

test
test: add test cases for service/user

controller: finish sign controller

---

app/public/stylesheets/style.less
app/view/sign/signin.html
app/view/sign/signup.html

Ref: issue https://github.com/cnodejs/nodeclub/issues/973
view && style
fix github login btn style

fix: github login button style

---

test/app/service/cache.test.js
test/app/service/mail.test.js
test/app/service/topic.test.js

test
add service cache unit test

test: add service cache unit test

---

app/service/at.js
app/service/message.js
test/app/service/at.test.js

test: add service at unit test

---

test/app/service/topic.test.js
test/app/service/topic_collect.test.js

test
add service topic_collect unit test

test: add service topic_collect unit test

---

app.js
app/controller/user.js
app/middleware/admin_required.js
app/middleware/auth_user.js
app/middleware/user_required.js
app/view/user/user.html
test/app/controller/user.test.js

passport 
refactor: admin inject & ut

refactor: admin inject & ut

---

app/controller/topic.js
app/view/index.html
app/view/topic/abstract.html
app/view/topic/list.html
test/app/controller/topic.test.js
test/app/service/topic.test.js

make the test case pass

---

test/app/controller/search.test.js

Ref: issue #61
test
search unit test

test: add controller search unit test

---

test/app/controller/rss.test.js

Ref: issue #61
test
add rss unit test

test: add rss unit test

---

app/controller/topic.js
app/middleware/error_page.js
app/router.js
app/service/topic.js
app/view/reply/reply.html
app/view/topic/index.html
app/view/user/index.html
test/app/controller/topic.test.js
test/app/service/topic.test.js

test:  improve controller topic unit test cov

---

README.md
config/config.default.js
config/plugin.prod.js
docker-compose.yml

- update README.md
- enable alinode while env === prod

chore: update deploy docs & enable alinode

---

app/controller/page.js
app/controller/sign.js
app/controller/user.js
app/view/layout.html
app/view/sidebar.html
app/view/static/about.html
app/view/static/api.html
app/view/static/faq.html
app/view/static/getstart.html
app/view/user/collect_topics.html
app/view/user/index.html
app/view/user/replies.html
app/view/user/topics.html
config/config.default.js
test/app/controller/sign.test.js

chore: make page title readable and fix the bug

---

app.js
app/controller/user.js
config/config.default.js
test/app/controller/user.test.js

controller/user
- fix some bug
- controller/user unit test.

Test: Improve controller/user ut coverage & bug fix

---

app/controller/sign.js
app/view/sign/reset.html
test/app/controller/sign.test.js

test: improve controller sign unit test coverage

---

app/controller/message.js
app/controller/reply.js
app/controller/topic.js
app/controller/user.js
app/router.js
app/service/at.js
app/service/message.js
app/view/message/index.html
app/view/message/message.html
app/view/sign/signin.html
test/app/controller/message.test.js
test/app/service/at.test.js
test/app/service/message.test.js
test/app/service/reply.test.js

refactor: message related

---

app/view/sidebar.html

fix: `no_reply_topics` display

---

.gitignore
app/middleware/locals.js
package.json

feat: add npm run assets

---

app/controller/user.js
app/middleware/block_user.js
app/router.js
config/config.default.js
test/app/controller/user.test.js

feat: add blockUser middleware

---

app.js
app/middleware/create_user_limit.js
app/router.js

fix: add githubId into user model

---

app/view/topic/abstract.html

fix: last reply time bug

---

Dockerfile
README.md
app/view/topic/abstract.html
docker-compose.yml
tutorials/Docker.md

- enable: Docker Automated build
- issue: #50
- issue: #77

docs: add docker support tutorial

---

app/controller/reply.js
app/view/topic/index.html
app/view/user/setting.html

views
修复回复历史无法查看问题，以及页面未加载完毕时「回复历史」框闪现

fix: reply history

---

app/view/layout.html
config/config.default.js

fix: favicon path

---

app/view/layout.html

fix: source code url

---

app/controller/search.js
app/controller/user.js
app/public/stylesheets/style.less
app/service/search.js
app/service/user.js
app/view/search/index.html
config/config.default.js
test/app/controller/search.test.js
test/app/controller/user.test.js
test/app/service/search.test.js

search
- search add baidu, local mode
- contorller search ut

Feature: Add search mode: local, google, baidu and UT

---

.snyk
app/controller/topic.js
app/extend/helper.js
app/router.js
app/service/topic.js
config/config.default.js
package.json
test/app/controller/topic.test.js

fix: upload file

---

app.js
app/controller/topic.js
app/router.js
app/service/reply.js
bin/generate_access_token.js
package.json

This reverts commit 314773f74392458dba86dab139e6e6abe37f4249.

Revert "Revert "新用户accessToken缺失；topic展示的边缘条件兼容""

---

app/controller/api/message.js
app/router/api.js
test/app/controller/api/message.test.js

Ref issue: #125 
api
add message api

feat: add message api

---

app/controller/api/topic.js
app/middleware/pagination.js
app/router/api.js
config/config.default.js
config/plugin.js
package.json
test/app/controller/api/topic.test.js
test/app/controller/reply.test.js
test/app/service/reply.test.js

Ref issue: #125
* add topic api
* add egg-router-plus to make sub router（增加子路由）
* fix reply unit test error content（修复错误的测试内容）
* add middleware pagination （更方便的计算分页）

fest: add topic api

---

app/controller/api/reply.js
app/router/api.js
test/app/controller/api/reply.test.js

api
- add reply api
Finish #125 of topic

feat: add reply api

---

app/controller/api/collect.js
app/middleware/error_handler.js
app/router/api.js
config/config.default.js
test/app/controller/api/collect.test.js

closes #125, closes #113
api
add topic_collect api

feat: add topic_collect api

---

app/controller/api/message.js

1) Use `ES6` syntax to rewrite `readMessages`/`unreadMessages` instead
of using index for a whole array.
2) Use Promise.all to wrap the mapping from read/unread messages and do
Promise.all to await to save time.

Refactor and optimize `list()`

---

bin/generate_access_token.js
config/config.default.js

Add connect MongoDB retry options(#133)

---

app/controller/user.js

refactor: remove the ctx
